
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild-Version 17.13.9+e0f243f1e f├╝r .NET Framework
      Der Buildvorgang wurde am 16.02.2025 08:51:06 gestartet.
      
      Projekt "C:\\Users\\Andrey\\Desktop\\open62541-1_4_10\\open62541-build32\\CMakeFiles\\3.31.5\\CompilerIdC\\CompilerIdC.vcxproj" auf Knoten "1" (Standardziele).
      PrepareForBuild:
        Das Verzeichnis "Debug\\" wird erstellt.
        Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
        Das Verzeichnis "Debug\\CompilerIdC.tlog\\" wird erstellt.
      InitializeBuildStatus:
        "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
        Aktualisieren des Timestamps von "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /analyze- /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\Andrey\\Desktop\\open62541-1_4_10\\open62541-build32\\CMakeFiles\\3.31.5\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.43.34808\\bin\\Hostx64\\x86\\cl.exe
      FinalizeBuildStatus:
        Die Datei "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" wird gel├Âscht.
        Aktualisieren des Timestamps von "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Die Erstellung von Projekt "C:\\Users\\Andrey\\Desktop\\open62541-1_4_10\\open62541-build32\\CMakeFiles\\3.31.5\\CompilerIdC\\CompilerIdC.vcxproj" ist abgeschlossen (Standardziele).
      
      Der Buildvorgang wurde erfolgreich ausgef├╝hrt.
          0 Warnung(en)
          0 Fehler
      
      Verstrichene Zeit 00:00:00.94
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/Andrey/Desktop/open62541-1_4_10/open62541-build32/CMakeFiles/3.31.5/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:5 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Andrey/Desktop/open62541-1_4_10/open62541-build32/CMakeFiles/CMakeScratch/TryCompile-wicmp4"
      binary: "C:/Users/Andrey/Desktop/open62541-1_4_10/open62541-build32/CMakeFiles/CMakeScratch/TryCompile-wicmp4"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Andrey/Desktop/open62541-1_4_10/open62541-build32/CMakeFiles/CMakeScratch/TryCompile-wicmp4'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Professional/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_8380d.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=17.0 /v:n
        MSBuild-Version 17.13.9+e0f243f1e f├╝r .NET Framework
        Der Buildvorgang wurde am 16.02.2025 08:51:08 gestartet.
        
        Projekt "C:\\Users\\Andrey\\Desktop\\open62541-1_4_10\\open62541-build32\\CMakeFiles\\CMakeScratch\\TryCompile-wicmp4\\cmTC_8380d.vcxproj" auf Knoten "1" (Standardziele).
        PrepareForBuild:
          Das Verzeichnis "cmTC_8380d.dir\\Debug\\" wird erstellt.
          Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
          Das Verzeichnis "C:\\Users\\Andrey\\Desktop\\open62541-1_4_10\\open62541-build32\\CMakeFiles\\CMakeScratch\\TryCompile-wicmp4\\Debug\\" wird erstellt.
          Das Verzeichnis "cmTC_8380d.dir\\Debug\\cmTC_8380d.tlog\\" wird erstellt.
        InitializeBuildStatus:
          "cmTC_8380d.dir\\Debug\\cmTC_8380d.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
          Aktualisieren des Timestamps von "cmTC_8380d.dir\\Debug\\cmTC_8380d.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /RTC1 /MDd /GS /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8380d.dir\\Debug\\\\" /Fd"cmTC_8380d.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.31\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.43.34808 for x86
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /RTC1 /MDd /GS /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8380d.dir\\Debug\\\\" /Fd"cmTC_8380d.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.31\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\Andrey\\Desktop\\open62541-1_4_10\\open62541-build32\\CMakeFiles\\CMakeScratch\\TryCompile-wicmp4\\Debug\\cmTC_8380d.exe" /INCREMENTAL /ILK:"cmTC_8380d.dir\\Debug\\cmTC_8380d.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/Andrey/Desktop/open62541-1_4_10/open62541-build32/CMakeFiles/CMakeScratch/TryCompile-wicmp4/Debug/cmTC_8380d.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Andrey/Desktop/open62541-1_4_10/open62541-build32/CMakeFiles/CMakeScratch/TryCompile-wicmp4/Debug/cmTC_8380d.lib" /MACHINE:X86  /machine:X86 cmTC_8380d.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_8380d.vcxproj -> C:\\Users\\Andrey\\Desktop\\open62541-1_4_10\\open62541-build32\\CMakeFiles\\CMakeScratch\\TryCompile-wicmp4\\Debug\\cmTC_8380d.exe
        FinalizeBuildStatus:
          Die Datei "cmTC_8380d.dir\\Debug\\cmTC_8380d.tlog\\unsuccessfulbuild" wird gel├Âscht.
          Aktualisieren des Timestamps von "cmTC_8380d.dir\\Debug\\cmTC_8380d.tlog\\cmTC_8380d.lastbuildstate".
        Die Erstellung von Projekt "C:\\Users\\Andrey\\Desktop\\open62541-1_4_10\\open62541-build32\\CMakeFiles\\CMakeScratch\\TryCompile-wicmp4\\cmTC_8380d.vcxproj" ist abgeschlossen (Standardziele).
        
        Der Buildvorgang wurde erfolgreich ausgef├╝hrt.
            0 Warnung(en)
            0 Fehler
        
        Verstrichene Zeit 00:00:02.13
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'C': C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.43.34808/bin/HostX64/x86/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:255 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Running the C compiler's linker: "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.43.34808/bin/HostX64/x86/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.43.34808.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
